# Cloudflare Tunnel Configuration Template
# Copy to ~/.cloudflared/config.yml and replace placeholders

tunnel: 7bbb8d12-6cf4-4556-8c5f-006fb7bab126
credentials-file: /home/chris/.cloudflared/7bbb8d12-6cf4-4556-8c5f-006fb7bab126.json

ingress:
  # SIMPLIFIED: Main domain routing with subpaths only
  # All traffic to chrislawrence.ca goes to Caddy on port 80
  # Caddy handles all subpath routing internally:
  #   - chrislawrence.ca/dashboard → Organizr
  #   - chrislawrence.ca/uptime → Uptime Kuma  
  #   - chrislawrence.ca/docker → Portainer
  #   - chrislawrence.ca/metrics → Grafana
  #   - etc.
  - hostname: chrislawrence.ca
    service: http://localhost:80

  # Application domains (when ready for deployment)
  # - hostname: api.magicpages.chrislawrence.ca
  #   service: http://localhost:8100
  # - hostname: magicpages.chrislawrence.ca
  #   service: http://localhost:8101
  # - hostname: portfolio.chrislawrence.ca
  #   service: http://localhost:8110
  # - hostname: capitolscope.chrislawrence.ca
  #   service: http://localhost:8120
  # - hostname: schedshare.chrislawrence.ca
  #   service: http://localhost:8130

  # Future production domains (when ready)
  # - hostname: api.magicpages.com
  #   service: http://localhost:8100
  # - hostname: magicpages.com
  #   service: http://localhost:8101

  # Catch-all for 404s
  - service: http_status:404

# DEPLOYMENT INSTRUCTIONS:
# 1. Copy this file to ~/.cloudflared/config.yml
# 2. Ensure credentials file exists at the specified path
# 3. Restart cloudflared: sudo systemctl restart cloudflared
# 4. Test tunnel: cloudflared tunnel run hephaestus-homelab
