# Hephaestus Homelab - Infrastructure Services Only
# Dell OptiPlex 7040 Ubuntu Server 24.04
# Docker Engine 27.x

networks:
  homelab-web:
    external: true

volumes:
  portainer_data:
  uptime-kuma_data:
  caddy_data:
  caddy_config:

services:
  # ============================================================================
  # INFRASTRUCTURE SERVICES
  # ============================================================================
  
  # Note: Caddy and Cloudflared are managed by the proxy stack
  # See: ./proxy/docker-compose.yml

  # Portainer - Docker management UI
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    networks:
      - homelab-web
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    security_opt:
      - no-new-privileges:true

  # Uptime Kuma - Uptime monitoring
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: unless-stopped
    networks:
      - homelab-web
    ports:
      - "3001:3001"
    volumes:
      - ./data/uptime-kuma:/app/data
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    security_opt:
      - no-new-privileges:true

  # Watchtower - Automatic container updates
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_SCHEDULE=0 0 4 * * *  # 4 AM daily
      - TZ=${TZ:-America/New_York}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  # ============================================================================
  # UTILITY SERVICES
  # ============================================================================

  # Glances - System monitoring
  glances:
    image: nicolargo/glances:latest
    container_name: glances
    restart: unless-stopped
    networks:
      - homelab-web
    ports:
      - "61208:61208"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - GLANCES_OPT=-w
    pid: host
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  # IT-Tools - Network utilities
  it-tools:
    image: corentinth/it-tools:latest
    container_name: it-tools
    restart: unless-stopped
    networks:
      - homelab-web
    ports:
      - "8081:80"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    security_opt:
      - no-new-privileges:true

  # ============================================================================
  # DASHBOARD SERVICES
  # ============================================================================

  # Organizr - Central dashboard for all services
  organizr:
    image: organizr/organizr:latest
    container_name: organizr
    restart: unless-stopped
    networks:
      - homelab-web
    ports:
      - "8082:80"
    volumes:
      - ./data/organizr:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-America/New_York}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    security_opt:
      - no-new-privileges:true
